culinary:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${culinary.serviceRegistry.username}:${culinary.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost